export const FETCH_MOVIE = "FETCH_MOVIE";
export const FETCH_MOVIES = "FETCH_MOVIES";
export const FETCH_MOVIE_SUCCESS = "FETCH_MOVIE_SUCCESS";
export const FETCH_MOVIES_SUCCESS = "FETCH_MOVIES_SUCCESS";
export const SHOW_SEARCHBAR = 'SHOW_SEARCHBAR';
export const HIDE_SEARCHBAR = 'HIDE_SEARCHBAR';
